services:
  redis:
    image: redis:7-alpine
    container_name: redis-single
    command: >
      redis-server
      --port 6379
      --appendonly yes
      --protected-mode no
      --bind 0.0.0.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  redis-data:
